server:
  port: 8022
#  tomcat:
#    uri-encoding: UTF-8
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp
#      suffix: .jsp
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
